services:
  - type: web
    name: geological-analysis-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AIzaSyAU7-gL0iv0yuQZMMrZAHBALOOAbbsLk8I
        sync: false
      - key: f6b06de67e4eb110951aa40c1a3813d9
        sync: false
